// import { DateTime } from "luxon/src/datetime";

export interface InvestmentType {
    rfiRecordId: string,
    rfiCode: string,
    walletId: string,
    userId: string,
    firstName: string,
    lastName: string,
    phone: string,
    email: string,
    investorFundingWalletId: string,
    amount: number,
    duration: number,
    isRolloverActivated: boolean,
    rolloverType: string | any,
    rolloverTarget: number,
    // rolloverDone: number,
    investmentTypeName: string,
    investmentTypeId: string,
    investmentType: string,
    tagName: string,
    currencyCode: string,
    interestRate: number,
    interestDueOnInvestment: number,
    totalAmountToPayout: number,
    lng: string,
    lat: string,
    principalPayoutStatus:string,
    interestPayoutStatus:string,
    // createdAt: DateTime,
    // startDate: DateTime,
    // payoutDate: DateTime,
    // isInvestmentApproved: boolean,
    // isPayoutSuccessful: boolean,
    // requestType: string,
    // approvalStatus: string,
    // currentState: string,
    // currentLGA: string,
    // status: string,
    // datePayoutWasDone: DateTime,
    // amountPaid: number,
    // amountOutstanding: number,
    // totalAmountPaidOnInvestment: number,
    // amountOutstandingOnInvestment: number,
    // totalAmountPaidOnInterest: number,
    // amountOutstandingOnInterest: number,
    // timeline: string,
    // checkedForPaymentAt: DateTime,
    // label: string,
}
