export interface SettingType {
    rfiName: string,
    rfiCode: string,
    rfiImageUrl: string,
    initiationNotificationEmail: Array<string>, // string,
    activationNotificationEmail: Array<string>, // string,
    maturityNotificationEmail: Array<string>, // string,
    payoutNotificationEmail: Array<string>, // string,
    rolloverNotificationEmail: Array<string>, // string,
    liquidationNotificationEmail: Array<string>, // string,
    isPayoutAutomated: boolean,
    fundingSourceTerminal: string,
    investmentWalletId: string,
    payoutWalletId: string,
    isInvestmentAutomated: boolean,
    isRolloverAutomated: boolean,
    isAllPayoutSuspended: boolean,
    isAllRolloverSuspended: boolean,
    liquidationPenalty: number,
    // investmentType: string,
    tagName: string,
    currencyCode: string,
}
