export interface SettingType {
    rfiName: string,
    rfiCode: string,
    rfiImageUrl: string,
    initiationNotificationEmail: string,
    activationNotificationEmail: string,
    maturityNotificationEmail: string,
    payoutNotificationEmail: string,
    rolloverNotificationEmail: string,
    liquidationNotificationEmail: string,
    isPayoutAutomated: boolean,
    fundingSourceTerminal: string,
    investmentWalletId: string,
    payoutWalletId: string,
    isInvestmentAutomated: boolean,
    isRolloverAutomated: boolean,
    isAllPayoutSuspended: boolean,
    isAllRolloverSuspended: boolean,
    // investmentType: string,
    tagName: string,
    currencyCode: string,
}
